### ISSUE TITLE
Implement a parse comments

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/npm-wpxml2md#63]

**Comment by akabekobeko** [comment]
Make the comment body indented code block.

  ```
  * ![anonymous](https://www.gravatar.com/avatar/beb21939f6a5a1e3b48faa2d5eed358a?d=identicon) **anonymous** 2017-12-28T04:59:53Z
    ```
    
    aaaaaaaaaaaaaaaaaaa
    ```
  ```

Describing an indented code block immediately after the list, the code block is included in the list.

* ![anonymous](https://www.gravatar.com/avatar/beb21939f6a5a1e3b48faa2d5eed358a?d=identicon) **anonymous** 2017-12-28T04:59:53Z
  ```
  
  aaaaaaaaaaaaaaaaaaa
  ```

**Comment by akabekobeko** [comment]
Code block is `<pre>` and `<code>`, it is not suitable for displaying sentences. So `<blockquote>` it.

**Comment by mukururo** [comment]
Suitable

**Comment by mukururo** [comment]
I didn't mean unsubscribe.not me

**Comment by mukururo** [comment]
Don't unsubscribe
